version: 2
jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.6.0-node-browsers-legacy
        environment:
          RAILS_ENV: 'test'
          POSTGRES_HOST: '127.0.0.1'
      - image: circleci/postgres:13.3
        environment:
          POSTGRES_HOST_AUTH_METHOD: 'true'
          POSTGRES_USER: 'mscrtins'
          POSTGRES_DB: 'ci_test'

    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.2.25
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      
      - run: yarn install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2
  rspec:
    jobs:
      - rspec:
          requires: